local command = {}

command.description = "ban a user!"
command.group = "Owner"

--================================================
-- Functions
--================================================


--================================================
-- on command Registered
--================================================
command.init = function(api)

end

--================================================
-- on command Execute
--================================================
command.onExecute = function(api, player, args)
    local targetName = args[1]
    local targetName = args[1]

    

end

return command